---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudkit.openshift.io
  resources:
  - clusterorders
  - hostpools
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudkit.openshift.io
  resources:
  - clusterorders/finalizers
  - hostpools/finalizers
  - virtualmachines/finalizers
  verbs:
  - update
- apiGroups:
  - cloudkit.openshift.io
  resources:
  - clusterorders/status
  - hostpools/status
  - virtualmachines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hypershift.openshift.io
  resources:
  - hostedclusters
  - nodepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
