apiVersion: cloudkit.openshift.io/v1alpha1
kind: ClusterOrder
metadata:
  labels:
    app.kubernetes.io/name: cloudkit-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterorder-sample
spec:
  templateID: cloudkit.templates.ocp_4_17_small
  nodeRequests:
  - resourceClass: fc430
    numberOfNodes: 2
